// Original by KevinVG207
// Uma-Carotene-TL/src/ui/common.py
const categories: { [key: string]: string } = {
    "1": "Error Descriptions",
    "2": "Error Titles",
    "3": "Tutorials",
    "4": "Character: Outfit Name",
    "5": "Character: Outfit",
    "6": "Character: Names",
    "7": "Voice Actor Names",
    "8": "Profile: Dorm",
    "9": "Profile: Weight",
    "10": "Item Descriptions (Tap & Hold)",
    "13": "Gacha Descriptions",
    "14": "Outfit Names",
    "15": "Outfit Descriptions",
    "16": "Song Titles",
    "17": "Song Credits",
    "23": "Item Names",
    "24": "Item Descriptions",
    "25": "Item Acquisition Methods",
    "26": "Gacha Banners",
    "27": "Tazuna Career Predictions",
    "28": "Race Names (Long)",
    "29": "Race Names (Short)",
    "31": "Racecourse Names (Set 1)",
    "32": "Race Names (Set 3)",
    "33": "Race Names (Set 4)",
    "34": "Racecourse Names (Set 2)",
    "35": "Race City Names (Set 1)",
    "36": "Race Names (Set 5)",
    "38": "Race Names (Short Set 2)",
    "39": "Shop Promotion & Items",
    "40": "Shop Promotion Descriptions",
    "41": "Item Exchange Conditions",
    "42": "Shop Currency (Carats)",
    "47": "Skill Names",
    "48": "Skill Descriptions",
    "49": "Carat Amounts",
    "55": "Training / Recreation Types",
    "59": "Race Mobs: Name",
    "63": "Help Button Text",
    "64": "Reward Descriptions",
    "65": "Titles",
    "66": "Title Descriptions",
    "67": "Missions",
    "68": "Secrets & Tips / Comics Headers",
    "69": "Secrets & Tips / Comics",
    "70": "Login Bonuses",
    "75": "Support Card Title Name",
    "76": "Support Card Title",
    "77": "Support Card Names",
    "78": "Support Card Names (Phonetic)",
    "88": "Support Card Stories",
    "91": "Main Story: Act",
    "92": "Umamusume Story Episodes",
    "93": "Main Story: Chapter Strings",
    "94": "Main Story: Episode Names",
    "95": "Main Story: Character Names",
    "96": "Main Story: Episode Text",
    "97": "Tazuna Career Tips",
    "111": "Graded Race Names",
    "112": "Main Story Chapters",
    "113": "Star Pieces",
    "114": "Star Piece Descriptions",
    "119": "Scenario Names",
    "120": "Scenario Introductions",
    "121": "Umamusume Classes",
    "128": "Jukebox Song Descriptions",
    "129": "(Deprecated in JP) SP & Monies",
    "130": "Honor Titles",
    "131": "Honor Title Requirements",
    "132": "Daily Races",
    "133": "Items (Alt Set)",
    "136": "Chat Texts",
    "138": "Training Names (Career)",
    "139": "Reporter Otonashi Dialogue (Career)",
    "140": "Race History Info (Part 1)",
    "141": "Race History Info (Part 2)",
    "142": "Career Conditions",
    "143": "Career Condition Descriptions",
    "144": "Profile: About",
    "147": "Spark Names",
    "148": "Team Trials Bonuses",
    "150": "Support Card Unique Perk",
    "151": "Support Card Effects",
    "152": "NPC Names (Set 1)",
    "154": "Support Card Effect Descriptions",
    "155": "Support Card Unique Perk Effects",
    "157": "Profile: Birthday",
    "158": "Profile: Height",
    "159": "Race: Styles",
    "160": "Race: Tracks",
    "161": "Race: Distances",
    "162": "Profile: School Year",
    "163": "Profile: Self-Intro",
    "164": "Profile: Likes",
    "165": "Profile: Dislikes",
    "166": "Profile: Ears",
    "167": "Profile: Tail",
    "168": "Profile: Shoe Size",
    "169": "Profile: Family",
    "170": "Character: Names (Set 3)",
    "171": "Random Event Requirements",
    "172": "Spark Details",
    "173": "NPC Job Titles",
    "174": "Unity Cup Scenario Characters",
    "175": "Profile: Categories",
    "176": "Recovery Items (Set 1)",
    "177": "Career Raffle Items",
    "178": "Career Random Items (Set 1)",
    "179": "Career Random Items (Set 2)",
    "180": "Career Random Items (Set 3)",
    "181": "Training Events",
    "182": "Character: Names (Katakana)",
    "184": "Push Notifications (TP)",
    "185": "Push Notifications (RP)",
    "186": "Support Card Tutorials",
    "187": "Campaign: Names",
    "188": "Campaign: Descriptions",
    "189": "Story Event Names",
    "190": "Story Event Missions",
    "191": "Story Event Episodes",
    "192": "Locations (Set 2)",
    "193": "Unity Cup Scenario (Part 1)",
    "194": "Unity Cup Scenario (Part 2)",
    "195": "Unity Cup Scenario (Part 3)",
    "196": "Event Notice Board",
    "197": "Recovery Items (Set 2)",
    "198": "Scenario Bonus Text (Set 1)",
    "199": "Scenario Bonus Text (Set 2)",
    "200": "Scenario Bonus Text (Set 3)",
    "201": "Monthly Twinkle (Set 1)",
    "202": "Monthly Twinkle (Set 2)",
    "203": "Monthly Twinkle (Set 3)",
    "204": "Monthly Twinkle (Set 4)",
    "205": "Monthly Twinkle (Set 5)",
    "206": "Champions Meeting Cups",
    "207": "Grand Concert Scenario (Part 1)",
    "208": "Grand Concert Scenario (Part 2)",
    "209": "Grand Concert Scenario (Part 3)",
    "210": "Grand Concert Scenario (Part 4)",
    "211": "Story Event Announcements",
    "212": "Obsolete Story Event Announcement",
    "214": "Story Event Titles (Short)",
    "215": "Special Transfers (Set 1)",
    "216": "Special Transfers (Set 2)",
    "217": "Special Transfers (Set 3)",
    "218": "Unity Cup Scenario (Part 4)",
    "220": "Special Transfers (Set 4)",
    "221": "Anniversary Texts",
    "222": "Anniversary Story Chapters",
    "223": "Locations (Set 1)",
    "225": "Trackblazer Scenario (Part 1)",
    "226": "Trackblazer Scenario (Part 2)",
    "227": "Trackblazer Scenario (Part 3)",
    "228": "Jukebox Character Text",
    "229": "Champions Meeting Race Text (Part 1)",
    "230": "Champions Meeting Race Text (Part 2)",
    "231": "Interview Questions",
    "232": "Interview Answers",
    "233": "Golshi Mode",
    "234": "Fuji Kiseki's Showtime (Part 1)",
    "235": "Fuji Kiseki's Showtime (Part 2)",
    "236": "Fuji Kiseki's Showtime (Part 3)",
    "237": "Scenario Names (Short)",
    "238": "Trackblazer Scenario (Part 4)",
    "239": "Fuji Kiseki's Showtime (Part 4)",
    "240": "Misc. Scenario Text (Set 1)",
    "241": "Racing Carnival",
    "242": "Racing Carnival (Part 1)",
    "243": "Race History Info (Part 3)",
    "244": "Race History Info (Part 4)",
    "245": "Racing Carnival (Part 2)",
    "246": "Fuji Kiseki's Showtime (Part 5)",
    "247": "Grand Concert Titles",
    "248": "Smart Falcon's Birthday Event (Part 1)",
    "249": "Grand Concert Title Requirements",
    "250": "Grand Concert Scenario (Part 6)",
    "251": "Grand Concert Scenario (Part 7)",
    "252": "Concert Theater Requirements",
    "253": "Smart Falcon's Birthday Event (Part 2)",
    "254": "Golshi Mode (Part 1)",
    "255": "Golshi Mode (Part 2)",
    "256": "Golshi Mode (Part 3)",
    "257": "Racing Carnival (Part 3)",
    "258": "Profile: Personal Rule",
    "259": "Profile: Phone Wallpaper",
    "260": "Profile: Before a Race...",
    "261": "Profile: Best Subjects",
    "262": "Profile: Humble Brag",
    "263": "Profile: Frequent Buys",
    "264": "NPC Names (Set 2)",
    "265": "Aim for the Stars! Dream Team",
    "266": "Streams & Paka Live TV Info",
    "267": "Career Critical Choices",
    "268": "Uma Outings' Locations",
    "269": "YouTube Redirect Strings",
    "270": "Grand Concert Scenario (Part 8)",
    "271": "Valentine Chocolate Messages (Part 1)",
    "272": "Valentine Chocolate Messages (Part 2)",
    "273": "Valentine Chocolate Names",
    "274": "League of Heroes (Part 1)",
    "275": "League of Heroes UI Text",
    "276": "IRL Live Performance Texts",
    "277": "IRL Live Game Gacha Tickets",
    "278": "NPC Names (Set 3)",
    "279": "(Deprecated) Event Schedule Text (Set 1)",
    "280": "(Deprecated) Christmas Text",
    "281": "(Deprecated) Event Schedule Text (Set 2)",
    "282": "Sparkly Magic Show Event Text (Part 1)",
    "283": "Anniversary Event Text (Part 1)",
    "284": "Sparkly Magic Show Event Text (Part 2)",
    "285": "Anniversary Event Text (Part 2)",
    "286": "Sparkly Magic Show Event Text (Part 3)",
    "287": "Campaign: Event Page Text",
    "288": "Event Schedule Text",
    "289": "Sparkly Magic Show Event Schedule Text",
    "290": "Skill Evolution Challenges",
    "293": "Uncategorized (293)",
    "294": "Grandmasters Scenario (Part 1)",
    "295": "Grandmasters Scenario (Part 2)",
    "296": "Grandmasters Scenario (Part 3)",
    "297": "League of Heroes Tazuna Text",
    "298": "Grandmasters Scenario (Part 4)",
    "299": "Grandmasters Scenario (Part 5)",
    "300": "Grandmasters Scenario (Part 6)",
    "301": "Tachyon Research Event",
    "302": "Victory Club Event",
    "303": "Victory Club Event (Part 1)",
    "304": "Victory Club Event (Part 2)",
    "305": "Victory Club Event (Part 3)",
    "306": "Victory Club Event (Part 4)",
    "307": "Victory Club Event (Part 5)",
    "308": "Victory Club Event (Part 6)",
    "309": "Victory Club Event (Part 7)",
    "310": "L'Arc Scenario (Part 1)",
    "311": "L'Arc Scenario (Part 2)",
    "312": "Victory Club Event (Part 8)",
    "313": "L'Arc Scenario (Part 3)",
    "314": "L'Arc Scenario (Part 4)",
    "315": "L'Arc Scenario (Part 5)",
    "316": "L'Arc Scenario (Part 6)",
    "317": "L'Arc Scenario (Part 7)",
    "318": "L'Arc Scenario (Part 8)",
    "319": "Special Transfers (Set 5)",
    "320": "Special Transfers (Set 6)",
    "321": "Special Transfers (Set 7)",
    "322": "L'Arc Scenario (Part 9)",
    "323": "U.A.F. Scenario (Part 1)",
    "325": "Event Prologues",
    "326": "All Scenario Texts #2",
    "327": "Special Shop Tickets",
    "328": "U.A.F. Scenario (Part 2)",
    "329": "U.A.F. Scenario (Part 3)",
    "330": "U.A.F. Scenario (Part 4)",
    "331": "Food Festival Scenario (Part 1)",
    "332": "Food Festival Scenario (Part 2)",
    "333": "Food Festival Scenario (Part 3)",
    "334": "Food Festival Scenario (Part 4)",
    "336": "Food Festival Scenario (Part 5)",
    "337": "U.A.F. Scenario (Part 5)",
    "338": "Mecha-Uma Scenario (Part 1)",
    "339": "Mecha-Uma Scenario (Part 2)",
    "340": "Mecha-Uma Scenario (Part 3)",
    "342": "Mecha-Uma Scenario (Part 4)",
    "343": "Mecha-Uma Scenario (Part 5)",
    "344": "Mecha-Uma Scenario (Part 6)",
    "345": "U.A.F. Scenario (Part 6)",
    "346": "Food Festival Scenario (Part 6)",
    "347": "U.A.F. Scenario (Part 7)",
    "348": "Food Festival Scenario (Part 7)",
    "349": "Food Festival Scenario (Part 8)",
    "350": "Anniversary (Unclear)",
    "351": "U.A.F. Scenario (Part 8)",
    "352": "Uncategorized (352)",
    "353": "Food Festival Scenario (Part 9)",
    "354": "Food Festival Scenario (Part 10)",
    "355": "Anniversary Related (Set 1)",
    "356": "Anniversary Related (Set 2)",
    "357": "Locations (Jobs)",
    "358": "Food Festival Scenario (Part 11)",
    "359": "Food Festival Scenario (Part 12)",
    "360": "Push Notifications (Jobs)",
    "361": "Food Festival Scenario (Part 13)",
    "362": "Description Texts (Jobs)",
    "363": "Legends Scenario (Part 1)",
    "364": "Legends Scenario (Part 2)",
    "365": "Mini Events Stuff (Set 1)",
    "366": "Mini Events Stuff (Set 2)",
    "367": "Mini Events Stuff (Set 3)",
    "368": "Mini Events Stuff (Set 4)",
    "369": "Legends Scenario (Part 3)",
    "370": "Legends Scenario (Part 4)",
    "371": "Legends Scenario (Part 5)",
    "372": "Character: Names (English)",
    "373": "Santa Anita Park Names",
    "374": "Design Your Island Scenario (Part 1)",
    "375": "Design Your Island Scenario (Part 2)",
    "376": "Character: Names (Short)",
    "377": "Subscription Text (Set 1)",
    "378": "Subscription Text (Set 2)",
    "379": "Subscription Text (Set 3)",
    "380": "Subscription Text (Set 4)",
    "381": "Subscription Text (Set 5)",
    "382": "Subscription Text (Set 6)",
    "383": "Design Your Island Scenario (Part 3)",
    "385": "Legends Scenario (Part 6)",
    "386": "Rental Decks",
    "387": "Guided Career Text (Set 1)",
    "388": "Guided Career Text (Set 2)",
    "389": "Guided Career Text (Set 3)",
    "390": "Guided Career Text (Set 4)",
    "391": "Guided Career Text (Set 5)",
    "392": "Guided Career Text (Set 6)",
    "393": "Guided Career Text (Set 7)",
    "394": "Outcomes Button",
    "397": "Yukoma Hot Spring Scenario (Part 1)",
    "398": "Yukoma Hot Spring Scenario (Part 2)",
    "399": "Yukoma Hot Spring Scenario (Part 3)",
    "400": "Design Your Island Scenario (Part 4)",
    "401": "Guided Career AI Descriptions",
    "402": "Yukoma Hot Spring Scenario (Part 4)",
    "403": "Gacha Roulette (Set 1)",
    "404": "Gacha Roulette (Set 2)",
    "407": "Yukoma Hot Spring Scenario (Part 5)",
    "408": "Yukoma Hot Spring Scenario (Part 6)",
    "409": "Yukoma Hot Spring Scenario (Part 7)",
    "410": "Guided Career Text (Set 8)",
    "411": "Champions Meeting Special Rules",
    "412": "Yukoma Hot Spring Scenario (Part 8)",
    "413": "Breeders' Cup Scenario (Part 1)",
    "414": "Breeders' Cup Scenario (Part 2)",
    "415": "Breeders' Cup Scenario (Part 3)",
    "416": "Uma Outings",
    "417": "Design Your Island Scenario (Part 5)",
    "418": "Design Your Island Scenario (Part 6)",
    "419": "Design Your Island Scenario (Part 7)",
    "420": "Breeders' Cup Scenario (Part 4)",
    "421": "Breeders' Cup Scenario (Part 5)",
    "422": "Yukoma Hot Spring Scenario (Part 9)",
    "423": "SiL Career Story Choices (Set 1)",
    "424": "SiL Career Story Choices (Set 2)",
    "425": "Breeders' Cup Scenario (Part 6)",
    "426": "Tracen Ramen Scenario (Part 1)",
    "427": "Tracen Ramen Scenario (Part 2)",
    "428": "Tracen Ramen Scenario (Part 3)",
    "429": "White Era Mini Event (Part 1)",
    "430": "Breeders' Cup Scenario (Part 7)",
    "431": "White Era Mini Event (Part 2)",
    "432": "Yukoma Hot Spring Scenario (Part 10)",
    "433": "League of Heroes (Part 2)",
    "434": "White Era Mini Event (Part 3)",
    "435": "Tracen Ramen Scenario (Part 4)",
    "444": "Transcend Career Story Choices (?)",
    "445": "White Era Mini Event (Part 4)",
    "446": "White Era Mini Event (Part 5)",
    "447": "White Era Mini Event (Part 6)",
    "448": "White Era Mini Event (Part 7)",
    "449": "Tracen Ramen Scenario (Part 5)",
    "450": "Race Log Text",
    "451": "Event Video Archive",
    "452": "League of Heroes (Part 3)",
    "453": "ST-2 Special Text",
    "454": "Breeders' Cup Scenario (Part 8)",
    "455": "Tracen Ramen Scenario (Part 6)",
    "456": "Race City Names (Set 2)",
    "457": "Breeders' Cup Scenario (Part 9)",
    "459": "Tracen Ramen Scenario (Part 7)",
    "460": "Tracen Ramen Scenario (Part 8)",
    "464": "Tracen Ramen Scenario (Part 9)",
    "465": "Tracen Ramen Scenario (Part 10)",
    "466": "Global Messed Up Database Entries",
    "467": "Tazuna Post-Race Tips (Set 1)",
    "468": "Tazuna Post-Race Tips (Set 2)",
    "469": "Push Notifications (Independent Training)",
    "475": "Tracen Ramen Scenario (Part 11)",
    "484": "Tracen Ramen Scenario (Part 12)",
    "485": "Tracen Ramen Scenario (Part 13)",
    "486": "Tracen Ramen Scenario (Part 14)",
    "487": "Tracen Ramen Scenario (Part 15)"
};
export default categories;